services:
- type: web
  name: WEBMI
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn WEBMI.wsgi:application
  envVars:
    - key: DJANGO_SETTINGS_MODULE
      value: WEBMI.settings
    - key: SECRET_KEY
      value: "django-insecure-w^o+z0!wres71vyl9b=4-&s^wacdrhnwjg+5f#f*7+pjbc^0@g"
    - key: ALLOWED_HOSTS
      value: webmi.onrender.com

